### ISSUE TITLE
python baidu_pic_downlowd.py -kw 闭眼人物 -dp 30

### ISSUE THREAD

**Issue by KangolHsu** [xymeow/baidu-picture-spider#1]
Traceback (most recent call last):
  File "baidu_pic_downlowd.py", line 43, in <module>
    imgData = json.loads(ipdata)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 15558 (char 15557)

**Comment by xymeow** [comment]
@KangolHsu The bug has been fixed, thanks for your report~
